### ISSUE TITLE
Bug: parsing error for skos ontology

### ISSUE THREAD

**Issue by RaimiSol** [ontoportal-lirmm/owlapi_wrapper#4]
I got a parsing error when parsing the skos ontology [ISOCOUNTRIES](https://biodiv-onto.gfbio.dev/ontologies/ISOCOUNTRIES)

Error message: owlapi.wrapper.OntologyParser - Optional.get() cannot be called on an absent value

Steps to reproduce:
1. clone repository master branch
2. compile: `mvn clean package`
3. java -DentityExpansionLimit=2500000 -Xmx10240M -jar ./target/owlapi-wrapper-1.4.2-SNAPSHOT.jar -m path/to/skos-ontology.rdf -o .. -r true

**Comment by syphax-bouazzouni** [comment]
Here, the issue is that this resource does not define an `owl:Ontology` object.

So here @jonquet, what do you decide for this case (Anonymous ontologies):

1. Ignone the error and parse the ontology without raising an exception (may work will just not extract metadata)
2. Not ignoring the error and raising the exception (the current state)

**Comment by syphax-bouazzouni** [comment]
I merged the fix https://github.com/ontoportal-lirmm/owlapi_wrapper/pull/5, choosing to ignore the submission that does not have owl:Ontology declared. (Option 1 above)

**Comment by jonquet** [comment]
I would have go for the option 1 too. Which is by the way the option I think was implemented so far... anyway.

**Comment by jonquet** [comment]
Note for later: https://agroportal.lirmm.fr/ontologies/BIODIVTHES parsed in September 2022 without a owl:Ontology declaration inside the file. 
Maybe the issue came later with the OWL-API

**Comment by jonquet** [comment]
Indeed. Just added an owl:Ontology ontology declaration to the source file (in the skos:ConceptScheme) and it worked for AGFOOD. Continue about the other problems in #438

So we can confirm now solution currently in lace/implemented is solution 2 above.
